# Generated by Django 3.0.7 on 2020-10-10 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201009_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 10, 11, 23, 50, 127313)),
        ),
    ]
